### ISSUE TITLE
"Upload failed"

### ISSUE THREAD

**Issue by Brin-o** [bcomnes/deploy-to-neocities#101]
Hello,

first of all thanks for this action it was very nice to use it with tiddlywiki on my neocities site. 

The action stopped functioning for me about 2 days ago, now only producing the following error in the deploy to neocities stage. Any idea how to fix this?

```
Run bcomnes/deploy-to-neocities@v1
[2](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:2)
  with:
[3](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:3)
    api_token: ***
[4](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:4)
    cleanup: false
[5](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:5)
    dist_dir: /
[6](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:7)
Starting inspecting stage...
[7](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:8)
Finished inspecting stage.
[8](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:9)
Starting diffing stage...
[9](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:10)
Finished diffing stage.
[10](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:11)
Starting applying stage...
[11](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:12)
Stage applying: 0.00% (0 B / 173 MB)
[12](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:13)
Stage applying: 21.01% (36.3 MB / 173 MB)
[13](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:14)
Stage applying: 60.57% (105 MB / 173 MB)
[14](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:15)
Stage applying: 100.00% (173 MB / 173 MB)
[15](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:16)
Finished error stage.
[16](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:17)
Error: Error uploading files
[17](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:18)
    at NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/webpack:/deploy-to-neocities/node_modules/async-neocities/index.js:356:1)
[18](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:19)
    at runMicrotasks (<anonymous>)
[19](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[20](https://github.com/Brin-o/neotown/actions/runs/3153267072/jobs/5129818483#step:3:21)
Error: Error uploading files
```

**Comment by bcomnes** [comment]
Looks like the error cause was trimmed from the stack trace, is there any more info available? 

Typically when files fail to upload to neocities, its because someone is trying to deploy their root project directory and it contains a `.git` or `node_modules` folder and the API rejects the file. If you figure out what kind of file is causing issues, let me know.

**Comment by bcomnes** [comment]
Looks like I sort of messed up error wrapping. I just cut a new release (https://github.com/bcomnes/deploy-to-neocities/releases/tag/v1.1.10) that fixes error wrapping and should contain more info now. Try again with that version or the v1 branch.

**Comment by Brin-o** [comment]
Hi! I don't know when you pushed the thing but it started working again around 2 days ago.

I **am however pushing the root directory!** But I can't see the .git folder anywhere on my neocities? So I'm guessing its getting filtered out somehow? Is that on your side or do you think the server is simply rejecting it?

I have a very normal static html website so there isn't any build process rn and everything is just in the root folder. I guess I could always make a folder inside of the git directory that contains the site in case I wanted to upload to neocities from somewhere where there is no .git folder.

**Comment by bcomnes** [comment]
Its safer to keep the site contents in a sub-folder if possible. I need to take a pass at default ignores still, but generally, avoiding these moving parts all together is the recommended strategy. Glad it started working.

**Comment by Brin-o** [comment]
Hi, I encountered another upload failed today. I finally, after that, moved my stuff to a subfolder but that did not fix things.

Looking at the log tho, I think it was backups of my tiddlywiki that are autogenerated that caused this error. The file names are very long which is why I think this happened.

Here is the full log: https://pipelines.actions.githubusercontent.com/serviceHosts/29339cb1-11d3-4b67-9d36-15cc0fb97344/_apis/pipelines/1/runs/228/signedlogcontent/2?urlExpires=2022-10-07T00%3A04%3A13.3739916Z&urlSigningMethod=HMACV1&urlSignature=Aax0cPXMQ%2Brqqi%2BZ4pUhquZdnS0Cne9ETQXGx5sXsuM%3D

Deleting the folder with the backups made the deploy successful so I'm 99% sure there is something with those files/names.

**Comment by bcomnes** [comment]
If you could pass an ignore glob as an upload setting, what would it look like?  I could maybe add that if it helps out.

**Comment by bcomnes** [comment]
Closing until I have more info.

**Comment by thebelovedmoon** [comment]
Idk if this relates to the whole thing, but I just found myself a block while trying to publish my site via your actions. attached below are the logs for convenience.

[logs_20.zip](https://github.com/bcomnes/deploy-to-neocities/files/12109553/logs_20.zip)
[repo](https://github.com/ReactOSPH/ReactSquad)

**Comment by bcomnes** [comment]
Hey @thebelovedmoon please search https://github.com/bcomnes/deploy-to-neocities/discussions for similar issues and open a fresh thread if you are still stuck.
