### ISSUE TITLE
deploy not working help

### ISSUE THREAD

**Issue by lime360** [bcomnes/deploy-to-neocities#109]
***log:***
```
Run bcomnes/deploy-to-neocities@v1
Starting inspecting stage...
Finished inspecting stage.
Starting diffing stage...
Finished diffing stage.
Starting applying stage...
Stage applying: 0.00% (0 B / 1.22 MB)
Stage applying: 100.00% (1.22 MB / 1.22 MB)
Finished error stage.
ErrorWithCause: Error uploading files
Files to upload: 
    at NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/webpack:/deploy-to-neocities/node_modules/async-neocities/index.js:35[6](https://github.com/lime360/website/actions/runs/3502937868/jobs/5867652293#step:3:7):1)
    at processTicksAndRejections (internal/process/task_queues.js:9[7](https://github.com/lime360/website/actions/runs/3502937868/jobs/5867652293#step:3:8):5)
caused by: ErrorWithCause: Neocities API error
    at NeocitiesAPIClient.batchPost (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/webpack:/deploy-to-neocities/node_modules/async-neocities/index.js:211:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
caused by: JSONHTTPError: Bad Request
    at handleResponse (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/webpack:/deploy-to-neocities/node_modules/fetch-errors/index.js:[8](https://github.com/lime360/website/actions/runs/3502937868/jobs/5867652293#step:3:9):1)
    at processTicksAndRejections (internal/process/task_queues.js:[9](https://github.com/lime360/website/actions/runs/3502937868/jobs/5867652293#step:3:10)7:5)
    at NeocitiesAPIClient.batchPost (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/webpack:/deploy-to-neocities/node_modules/async-neocities/index.js:208:1)
    at async Promise.all (index 0)
    at NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/webpack:/deploy-to-neocities/node_modules/async-neocities/index.js:353:1)
    at doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/webpack:/deploy-to-neocities/index.js:32:1)
[
  {
    name: 'hbaprilfoolsdemo/src/Runtime.js',
    path: '/home/runner/work/website/website/public/hbaprilfoolsdemo/src/Runtime.js'
  },
  {
    name: 'hbaprilfoolsdemo/resources/hoverboy april fools demo.cch',
    path: '/home/runner/work/website/website/public/hbaprilfoolsdemo/resources/hoverboy april fools demo.cch'
  },
  {
    name: 'hbaprilfoolsdemo/resources/hoverboy april fools demo.cc1',
    path: '/home/runner/work/website/website/public/hbaprilfoolsdemo/resources/hoverboy april fools demo.cc1'
  },
  {
    name: 'hbaprilfoolsdemo/resources/M0001.png',
    path: '/home/runner/work/website/website/public/hbaprilfoolsdemo/resources/M0001.png'
  },
  {
    name: 'hbaprilfoolsdemo/resources/9999.mp3',
    path: '/home/runner/work/website/website/public/hbaprilfoolsdemo/resources/9999.mp3'
  },
  {
    name: 'hbaprilfoolsdemo/resources/00[12](https://github.com/lime360/website/actions/runs/3502937868/jobs/5867652293#step:3:13).png',
    path: '/home/runner/work/website/website/public/hbaprilfoolsdemo/resources/0012.png'
  },
  {
    name: 'hbaprilfoolsdemo/index.html',
    path: '/home/runner/work/website/website/public/hbaprilfoolsdemo/index.html'
  },
  {
    name: 'assets/flash-badge.gif',
    path: '/home/runner/work/website/website/public/assets/flash-badge.gif'
  },
  {
    name: 'graphics.html',
    path: '/home/runner/work/website/website/public/graphics.html'
  },
  {
    name: 'nanoblog/index.html',
    path: '/home/runner/work/website/website/public/nanoblog/index.html'
  }
]
Error: Error uploading files
```

**Comment by bcomnes** [comment]
I'm guessing it's rejecting those `.cch` and `.cc1` files. I need to fix the error handing to include the body of the failed request.

**Comment by lime360** [comment]
i reuploaded the source of the files to my github site and it still not working

**Comment by lime360** [comment]
nevermind i found the issue and now deploy are working
