### ISSUE TITLE
Keep Encountering "Error Uploading Files"

### ISSUE THREAD

**Issue by lule345** [bcomnes/deploy-to-neocities#156]
##[debug]Evaluating condition for step: 'Deploy to neocities'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Deploy to neocities
##[debug]Loading inputs
##[debug]Evaluating: secrets.NEOCITIES_API_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'NEOCITIES_API_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run bcomnes/deploy-to-neocities@v1
Starting inspecting stage...
Finished inspecting stage.
Starting diffing stage...
Finished diffing stage.
Starting applying stage...
Stage applying: 0.00% (0 B / 13.1 MB)
Stage applying: 100.00% (13.1 MB / 13.1 MB)
Finished error stage.
_ErrorWithCause: Error uploading files
Files to upload: 
    at NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:[2](https://github.com/lule345/lules-oddities/actions/runs/6008260837/job/16295681290#step:4:2)07[3](https://github.com/lule345/lules-oddities/actions/runs/6008260837/job/16295681290#step:4:3)5:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:22532:17)
caused by: _ErrorWithCause: Neocities API error
    at NeocitiesAPIClient.batchPost (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:20608:3[4](https://github.com/lule345/lules-oddities/actions/runs/6008260837/job/16295681290#step:4:4))
[
  {
    name: 'text.txt',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/text.txt'
  },
  {
    name: 'img/img.txt',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/img/img.txt'
  },
  {
    name: 'img/favicon.ico',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/img/favicon.ico'
  },
  {
    name: 'img/Scientist_01.webp',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/img/Scientist_01.webp'
  },
  {
    name: 'img/F3rYzJMXEAAcLGf.jpg',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/img/F3rYzJMXEAAcLGf.jpg'
  },
  {
    name: 'img/F37Q398XAAAhi-f.jpg',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/img/F37Q398XAAAhi-f.jpg'
  },
  {
    name: 'directory.html',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/directory.html'
  },
  {
    name: 'audio/tias.mp4',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/audio/tias.mp4'
  },
  {
    name: 'audio/camerons_world_[dial-up_dub_version].mp3',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/audio/camerons_world_[dial-up_dub_version].mp3'
  },
  {
    name: 'audio/audio.txt',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/audio/audio.txt'
  },
  {
    name: 'index.html',
    path: '/home/runner/work/lules-oddities/lules-oddities/public/index.html'
  }
]
Error: Error uploading files
    at processTicksAndRejections (node:internal/process/task_queues:96:[5](https://github.com/lule345/lules-oddities/actions/runs/6008260837/job/16295681290#step:4:5))
    at async Promise.all (index 0)
    at async NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:20733:11)
    at async doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:22532:17)
caused by: JSONHTTPError: Bad Request
    at handleResponse (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:2219:40)
    at processTicksAndRejections (node:internal/process/task_queues:9[6](https://github.com/lule345/lules-oddities/actions/runs/6008260837/job/16295681290#step:4:6):5)
    at async NeocitiesAPIClient.batchPost (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:20605:28)
    at async Promise.all (index 0)
    at async NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:20[7](https://github.com/lule345/lules-oddities/actions/runs/6008260837/job/16295681290#step:4:7)33:[11](https://github.com/lule345/lules-oddities/actions/runs/6008260837/job/16295681290#step:4:11))
    at async doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/dist/index.js:22532:[17](https://github.com/lule345/lules-oddities/actions/runs/6008260837/job/16295681290#step:4:17))
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Deploy to neocities

GitHub attempted to deploy but errored out in the process, filling my entire email inbox lol. From what I've seen on other discussions, I checked my files and I should not have invalid files that Neocities can't upload. Maybe you can double check?

**Comment by bcomnes** [comment]
Yeah, sorry been a long running issue. the API errors out when you upload disallowed filetypes. I don't have an exhaustive list of what is disallowed or allowed so the best I can do is just filter out known bad file types. 

Do you have a filetype that you identified that was causing errors?

**Comment by lule345** [comment]
It was just MP3/MP4 files.

**Comment by bcomnes** [comment]
What size were they? I think there is a max file size validation on the api.

**Comment by bcomnes** [comment]
Fairly sure mp4/mp3 is allowed. iirc the file size maximum per file is like 25-50mb.

**Comment by lule345** [comment]
Alright
