### ISSUE TITLE
assert is not a function?

### ISSUE THREAD

**Issue by 1337god** [bcomnes/deploy-to-neocities#8]
```
Run bcomnes/deploy-to-neocities@v1.0.9
  with:
    api_token: 
    cleanup: true
    dist_dir: public
TypeError: assert is not a function
##[error]assert is not a function
    at doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1.0.9/index.js:14:1)
    at Object.104 (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1.0.9/index.js:31:1)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at startup (/webpack/bootstrap:34:1)
    at /webpack/bootstrap:38:1
    at Object.<anonymous> (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1.0.9/dist/index.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
```

**Comment by bcomnes** [comment]
Oops, introduced an error today. Fixing now.

**Comment by bcomnes** [comment]
Should be fixed now.  If you are running the v1 tag, it should auto update.
